const clinicalPatients = [
  {
    id: "PAC-001",
    record: "Historia 000184",
    name: "Maria Salas Rojas",
    document: "DNI 45871236",
    age: "42 anios",
    insurance: "Particular",
    appointment: "09:00",
    status: "En consulta",
    priority: "Alta",
    physician: "Dra. Vargas",
    reason: "Control de hipertension y cefalea",
    allergy: "Penicilina - reaccion anafilactica",
    chronic: "Hipertension arterial",
    lastVisit: "2026-06-03",
    vitals: {
      pressure: "145/92",
      heartRate: "88 lpm",
      respiratoryRate: "18 rpm",
      temperature: "36.8 C",
      oxygen: "97%",
      weight: "68 kg",
      height: "1.62 m",
      bmi: "25.9",
    },
    diagnoses: ["I10 - Hipertension esencial", "R51 - Cefalea"],
    medicines: ["Losartan 50 mg cada 24 h", "Paracetamol 500 mg condicional"],
    history: [
      ["2026-06-03", "Medicina interna", "Control HTA", "Cerrada"],
      ["2026-05-14", "Laboratorio", "Perfil lipidico", "Completado"],
      ["2026-04-20", "Medicina general", "Cefalea", "Firmada"],
    ],
    prescription: {
      code: "RX-1049",
      status: "Borrador",
      items: [
        ["Losartan 50 mg", "1 tableta", "Cada 24 h", "30 dias"],
        ["Paracetamol 500 mg", "1 tableta", "Cada 8 h si dolor", "5 dias"],
      ],
    },
    documents: [
      ["PDF", "Informe laboratorio", "2026-05-14", "Visible"],
      ["Imagen", "Radiografia torax", "2026-04-18", "Restringido"],
    ],
    audit: [
      ["08:52", "enfermeria01", "Registro de signos vitales", "Triaje"],
      ["09:04", "dra.vargas", "Apertura de consulta", "Consulta"],
      ["09:17", "dra.vargas", "Receta en borrador", "Recetas"],
    ],
    orders: [
      ["Laboratorio", "Perfil lipidico", "Normal", "Solicitada"],
      ["Control", "Presion domiciliaria", "Media", "Pendiente"],
    ],
  },
  {
    id: "PAC-002",
    record: "Historia 000219",
    name: "Luis Herrera Vega",
    document: "DNI 47200981",
    age: "36 anios",
    insurance: "Plan Familiar",
    appointment: "09:30",
    status: "Triaje listo",
    priority: "Media",
    physician: "Dr. Ramos",
    reason: "Dolor lumbar",
    allergy: "Sin alergias registradas",
    chronic: "Ninguna declarada",
    lastVisit: "2026-05-26",
    vitals: {
      pressure: "118/76",
      heartRate: "74 lpm",
      respiratoryRate: "17 rpm",
      temperature: "36.4 C",
      oxygen: "98%",
      weight: "81 kg",
      height: "1.75 m",
      bmi: "26.4",
    },
    diagnoses: ["M54.5 - Lumbalgia"],
    medicines: ["Ibuprofeno 400 mg por 3 dias"],
    history: [
      ["2026-05-26", "Traumatologia", "Dolor lumbar", "Cerrada"],
      ["2026-02-11", "Medicina general", "Infeccion respiratoria", "Firmada"],
    ],
    prescription: {
      code: "RX-1050",
      status: "Emitida",
      items: [["Ibuprofeno 400 mg", "1 tableta", "Cada 8 h", "3 dias"]],
    },
    documents: [["PDF", "Informe externo", "2026-05-25", "Visible"]],
    audit: [
      ["09:18", "enfermeria02", "Triaje completado", "Triaje"],
      ["09:21", "dr.ramos", "Consulta asignada", "Consulta"],
    ],
    orders: [["Imagen", "Radiografia lumbar", "Normal", "Pendiente"]],
  },
  {
    id: "PAC-003",
    record: "Historia 000301",
    name: "Rosa Medina Torres",
    document: "DNI 40123877",
    age: "58 anios",
    insurance: "Seguro Clinica",
    appointment: "10:00",
    status: "Pendiente triaje",
    priority: "Alta",
    physician: "Dra. Leon",
    reason: "Control diabetes",
    allergy: "Metamizol - urticaria",
    chronic: "Diabetes mellitus tipo 2",
    lastVisit: "2026-06-12",
    vitals: {
      pressure: "132/84",
      heartRate: "82 lpm",
      respiratoryRate: "19 rpm",
      temperature: "36.7 C",
      oxygen: "96%",
      weight: "72 kg",
      height: "1.58 m",
      bmi: "28.8",
    },
    diagnoses: ["E11 - Diabetes mellitus tipo 2"],
    medicines: ["Metformina 850 mg cada 12 h"],
    history: [
      ["2026-06-12", "Endocrinologia", "Control glucosa", "Cerrada"],
      ["2026-04-02", "Laboratorio", "Hemoglobina glicosilada", "Completado"],
    ],
    prescription: {
      code: "RX-1051",
      status: "Firmada",
      items: [["Metformina 850 mg", "1 tableta", "Cada 12 h", "30 dias"]],
    },
    documents: [["PDF", "HbA1c", "2026-04-02", "Visible"]],
    audit: [["08:35", "recepcion01", "Apertura de atencion", "Admision"]],
    orders: [["Laboratorio", "Hemoglobina glicosilada", "Alta", "Sugerida"]],
  },
];

const clinicalCareSteps = [
  ["Admision", "Paciente validado", "Datos y cobertura listos", "done"],
  ["Triaje", "Signos registrados", "Prioridad asignada", "done"],
  ["Consulta", "Evaluacion medica", "Diagnostico y plan", "active"],
  ["Cierre", "Revision final", "Firma pendiente", "pending"],
  ["Farmacia", "Receta preparada", "Entrega por validar", "pending"],
];

const clinicalSubmodules = [
  ["historia-clinica", "Panel clinico", "Vista principal", "resumen"],
  ["historia-triaje", "Triaje y signos", "Enfermeria", "triaje"],
  ["historia-consulta", "Consulta medica", "Atencion", "consulta"],
  ["historia-ordenes", "Ordenes", "Laboratorio e imagenes", "ordenes"],
  ["historia-recetas", "Recetas", "Prescripcion", "receta"],
  ["historia-documentos", "Documentos", "Archivos clinicos", "documentos"],
  ["historia-auditoria", "Auditoria", "Trazabilidad", "auditoria"],
];

window.GestionApp.registerAdminGroup({
  id: "historia-recetas",
  module: "Modulo",
  label: "Historia Clinica",
  screens: clinicalSubmodules.map(([id, title, useCase, initialTab]) => ({
    id,
    title,
    useCase,
    actor: "Equipo clinico",
    objective: "Operar el flujo completo de atencion del paciente.",
    layout: "clinical-system",
    initialTab,
    patients: clinicalPatients,
    careSteps: clinicalCareSteps,
  })),
});
