window.GestionApp.registerAdminGroup({
  id: "historia-recetas",
  module: "Módulo",
  label: "Historia Clínica Electronica y Recetas",
  screens: [
    {
      id: "historia-clinica",
      title: "Historia clínica electrónica",
      useCase: "Consultar historial",
      actor: "Médico",
      objective: "Revisar antecedentes, alergias, consultas previas, diagnósticos y tratamientos.",
      metrics: [["Consultas", "16", "Históricas"], ["Alergias", "1", "Registrada"], ["Antecedentes", "4", "Activos"]],
      fields: ["Paciente", "Antecedentes", "Alergias", "Medicaciones", "Observación"],
      table: {
        headers: ["Fecha", "Servicio", "Diagnóstico", "Estado"],
        rows: [["2026-06-03", "Medicina", "Control HTA", "Cerrada"], ["2026-05-14", "Laboratorio", "Perfil lipídico", "Completado"], ["2026-04-20", "Medicina", "Cefalea", "Cerrada"]],
      },
      side: ["Línea clínica", "Alergias visibles", "Antecedentes relevantes"],
    },
    {
      id: "consulta-medica",
      title: "Consulta médica",
      useCase: "Registrar diagnóstico",
      actor: "Médico",
      objective: "Documentar anamnesis, examen físico, diagnóstico CIE-10 y plan de tratamiento.",
      metrics: [["Consultas", "12", "Hoy"], ["En espera", "8", "Cola"], ["Cerradas", "19", "Hoy"]],
      fields: ["Motivo", "Anamnesis", "Examen físico", "Diagnóstico", "Tratamiento", "Observaciones"],
      table: {
        headers: ["Paciente", "Diagnóstico", "Tratamiento", "Estado"],
        rows: [["Jorge Paredes", "Gastritis", "Omeprazol", "En atención"], ["Rosa Medina", "Diabetes", "Control", "Cerrada"], ["María Salas", "Hipertensión", "Losartán", "Receta emitida"]],
      },
      side: ["Historia visible", "Diagnóstico CIE-10", "Plan terapéutico"],
    },
    {
      id: "receta-medica",
      title: "Receta médica",
      useCase: "Emitir receta",
      actor: "Médico",
      objective: "Indicar medicamentos, dosis, frecuencia, duración e instrucciones para farmacia.",
      metrics: [["Emitidas", "14", "Hoy"], ["Pendientes", "6", "Farmacia"], ["Dispensadas", "8", "Hoy"]],
      fields: ["Medicamento", "Dosis", "Frecuencia", "Duración", "Indicaciones"],
      table: {
        headers: ["Receta", "Paciente", "Medicamento", "Estado"],
        rows: [["RX-1048", "Luis Herrera", "Amoxicilina 875 mg", "Pendiente"], ["RX-1049", "María Salas", "Losartán 50 mg", "Pendiente"], ["RX-1050", "Rosa Medina", "Metformina 850 mg", "Dispensada"]],
      },
      side: ["Validar stock", "Imprimir receta", "Enviar a farmacia"],
    },
    {
      id: "ordenes-medicas",
      title: "Órdenes médicas",
      useCase: "Solicitar laboratorio",
      actor: "Médico",
      objective: "Registrar órdenes de laboratorio, imágenes o procedimientos para seguimiento.",
      metrics: [["Órdenes", "9", "Hoy"], ["Laboratorio", "6", "Solicitudes"], ["Procedimientos", "3", "Pendientes"]],
      fields: ["Tipo de orden", "Prioridad", "Indicaciones", "Fecha requerida", "Profesional"],
      table: {
        headers: ["Orden", "Paciente", "Tipo", "Estado"],
        rows: [["OM-331", "Jorge Paredes", "Hemograma", "Solicitada"], ["OM-332", "Rosa Medina", "Glucosa", "Completada"], ["OM-333", "María Salas", "ECG", "Pendiente"]],
      },
      side: ["Orden ligada a consulta", "Estado de solicitud", "Seguimiento"],
    },
    {
      id: "evolucion-clinica",
      title: "Evolución clínica",
      useCase: "Registrar evolución",
      actor: "Médico",
      objective: "Registrar progreso del paciente, respuesta al tratamiento y próximos controles.",
      metrics: [["Evoluciones", "22", "Semana"], ["Controles", "11", "Programados"], ["Altas", "4", "Hoy"]],
      fields: ["Paciente", "Evolución", "Respuesta", "Plan", "Próximo control"],
      table: {
        headers: ["Paciente", "Última evolución", "Plan", "Estado"],
        rows: [["María Salas", "Presión estable", "Control 30 días", "Activo"], ["Rosa Medina", "Glucosa controlada", "Mantener dosis", "Activo"], ["Luis Herrera", "Dolor mejora", "Alta", "Cerrado"]],
      },
      side: ["Seguimiento médico", "Plan de control", "Cierre clínico"],
    },
  ],
});
