window.GestionApp.registerAdminGroup({
  id: "citas-agenda",
  module: "Módulo",
  label: "Gestión de Citas y Agenda",
  screens: [
    {
      id: "agenda-medica",
      title: "Agenda médica",
      useCase: "Consultar disponibilidad",
      actor: "Recepción",
      objective: "Visualizar horarios disponibles por médico, especialidad, sede y turno.",
      metrics: [["Citas hoy", "34", "Programadas"], ["Disponibles", "12", "Bloques libres"], ["Sobreturnos", "3", "Autorizados"]],
      fields: ["Fecha", "Especialidad", "Médico", "Sede", "Turno"],
      table: {
        headers: ["Hora", "Médico", "Especialidad", "Estado"],
        rows: [["09:00", "Dra. Vargas", "Medicina", "Ocupado"], ["10:30", "Dr. Ramos", "Medicina", "Libre"], ["12:00", "Dra. León", "Pediatría", "Reservado"]],
      },
      side: ["Filtro por médico", "Bloques disponibles", "Vista calendario"],
    },
    {
      id: "registrar-cita",
      title: "Registrar cita",
      useCase: "Agendar atención",
      actor: "Recepción / Paciente",
      objective: "Reservar una cita seleccionando paciente, especialidad, médico, fecha y horario.",
      metrics: [["Reservas", "21", "Hoy"], ["Nuevos", "6", "Primera vez"], ["Reprogramadas", "4", "Hoy"]],
      fields: ["Documento", "Paciente", "Especialidad", "Médico", "Fecha", "Hora"],
      table: {
        headers: ["Paciente", "Especialidad", "Fecha", "Estado"],
        rows: [["María Salas", "Medicina", "2026-06-29 09:00", "Confirmada"], ["Jorge Paredes", "Gastroenterología", "2026-06-29 10:30", "Pendiente"], ["Ana Torres", "Pediatría", "2026-06-30 11:00", "Confirmada"]],
      },
      side: ["Validar paciente", "Asignar horario", "Confirmación visible"],
    },
    {
      id: "confirmar-cita",
      title: "Confirmación de cita",
      useCase: "Confirmar asistencia",
      actor: "Recepción",
      objective: "Cambiar el estado de la cita a confirmada, pendiente, cancelada o no asistió.",
      metrics: [["Confirmadas", "28", "Hoy"], ["Pendientes", "6", "Contactar"], ["Canceladas", "2", "Hoy"]],
      fields: ["Cita", "Paciente", "Canal", "Estado", "Observación"],
      table: {
        headers: ["Cita", "Paciente", "Canal", "Estado"],
        rows: [["CT-1001", "María Salas", "WhatsApp", "Confirmada"], ["CT-1002", "Jorge Paredes", "Teléfono", "Pendiente"], ["CT-1003", "Rosa Medina", "Portal", "Confirmada"]],
      },
      side: ["Confirmar asistencia", "Registrar canal", "Reducir inasistencias"],
    },
    {
      id: "reprogramar-cita",
      title: "Reprogramar cita",
      useCase: "Cambiar fecha u horario",
      actor: "Recepción / Paciente",
      objective: "Mover una cita existente a otro horario disponible dejando trazabilidad visual.",
      metrics: [["Solicitudes", "7", "Semana"], ["Aprobadas", "5", "Recepción"], ["Pendientes", "2", "Paciente"]],
      fields: ["Cita actual", "Motivo", "Nueva fecha", "Nueva hora", "Responsable"],
      table: {
        headers: ["Paciente", "Anterior", "Nuevo horario", "Estado"],
        rows: [["María Salas", "29/06 09:00", "30/06 10:30", "Aprobada"], ["Luis Herrera", "29/06 11:00", "01/07 08:30", "Pendiente"], ["Ana Torres", "30/06 12:00", "30/06 16:00", "Aprobada"]],
      },
      side: ["Buscar disponibilidad", "Registrar motivo", "Notificar cambio"],
    },
    {
      id: "lista-espera",
      title: "Lista de espera",
      useCase: "Administrar pacientes en espera",
      actor: "Recepción",
      objective: "Mantener pacientes esperando cupo para especialidades con alta demanda.",
      metrics: [["En espera", "18", "Activos"], ["Prioritarios", "4", "Adulto mayor"], ["Asignados", "6", "Semana"]],
      fields: ["Paciente", "Especialidad", "Prioridad", "Disponibilidad", "Comentario"],
      table: {
        headers: ["Paciente", "Especialidad", "Prioridad", "Estado"],
        rows: [["Carlos Vega", "Cardiología", "Alta", "Esperando"], ["Ana Torres", "Pediatría", "Media", "Contactar"], ["Rosa Medina", "Endocrino", "Alta", "Asignada"]],
      },
      side: ["Priorizar pacientes", "Asignar cupo", "Control de demanda"],
    },
    {
      id: "calendario-medico",
      title: "Calendario del médico",
      useCase: "Revisar agenda diaria",
      actor: "Médico",
      objective: "Mostrar las citas del profesional con estados, tiempos y notas rápidas.",
      metrics: [["Pacientes", "12", "Turno"], ["Atendidos", "5", "Cerrados"], ["Restantes", "7", "Pendientes"]],
      fields: ["Médico", "Fecha", "Consultorio", "Estado", "Nota"],
      table: {
        headers: ["Hora", "Paciente", "Motivo", "Estado"],
        rows: [["09:00", "María Salas", "Control HTA", "En espera"], ["09:30", "Luis Herrera", "Dolor lumbar", "Atendido"], ["10:00", "Rosa Medina", "Diabetes", "En consulta"]],
      },
      side: ["Agenda por turno", "Estado del paciente", "Notas médicas rápidas"],
    },
  ],
});
